// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xcalculatephase.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XCalculatephase_CfgInitialize(XCalculatephase *InstancePtr, XCalculatephase_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Crtls_BaseAddress = ConfigPtr->Crtls_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XCalculatephase_Start(XCalculatephase *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCalculatephase_ReadReg(InstancePtr->Crtls_BaseAddress, XCALCULATEPHASE_CRTLS_ADDR_AP_CTRL) & 0x80;
    XCalculatephase_WriteReg(InstancePtr->Crtls_BaseAddress, XCALCULATEPHASE_CRTLS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XCalculatephase_IsDone(XCalculatephase *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCalculatephase_ReadReg(InstancePtr->Crtls_BaseAddress, XCALCULATEPHASE_CRTLS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XCalculatephase_IsIdle(XCalculatephase *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCalculatephase_ReadReg(InstancePtr->Crtls_BaseAddress, XCALCULATEPHASE_CRTLS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XCalculatephase_IsReady(XCalculatephase *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCalculatephase_ReadReg(InstancePtr->Crtls_BaseAddress, XCALCULATEPHASE_CRTLS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XCalculatephase_EnableAutoRestart(XCalculatephase *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCalculatephase_WriteReg(InstancePtr->Crtls_BaseAddress, XCALCULATEPHASE_CRTLS_ADDR_AP_CTRL, 0x80);
}

void XCalculatephase_DisableAutoRestart(XCalculatephase *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCalculatephase_WriteReg(InstancePtr->Crtls_BaseAddress, XCALCULATEPHASE_CRTLS_ADDR_AP_CTRL, 0);
}

u32 XCalculatephase_Get_return(XCalculatephase *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCalculatephase_ReadReg(InstancePtr->Crtls_BaseAddress, XCALCULATEPHASE_CRTLS_ADDR_AP_RETURN);
    return Data;
}
void XCalculatephase_Set_T_X(XCalculatephase *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCalculatephase_WriteReg(InstancePtr->Crtls_BaseAddress, XCALCULATEPHASE_CRTLS_ADDR_T_X_DATA, Data);
}

u32 XCalculatephase_Get_T_X(XCalculatephase *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCalculatephase_ReadReg(InstancePtr->Crtls_BaseAddress, XCALCULATEPHASE_CRTLS_ADDR_T_X_DATA);
    return Data;
}

void XCalculatephase_Set_T_Y(XCalculatephase *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCalculatephase_WriteReg(InstancePtr->Crtls_BaseAddress, XCALCULATEPHASE_CRTLS_ADDR_T_Y_DATA, Data);
}

u32 XCalculatephase_Get_T_Y(XCalculatephase *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCalculatephase_ReadReg(InstancePtr->Crtls_BaseAddress, XCALCULATEPHASE_CRTLS_ADDR_T_Y_DATA);
    return Data;
}

void XCalculatephase_Set_T_Z(XCalculatephase *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCalculatephase_WriteReg(InstancePtr->Crtls_BaseAddress, XCALCULATEPHASE_CRTLS_ADDR_T_Z_DATA, Data);
}

u32 XCalculatephase_Get_T_Z(XCalculatephase *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCalculatephase_ReadReg(InstancePtr->Crtls_BaseAddress, XCALCULATEPHASE_CRTLS_ADDR_T_Z_DATA);
    return Data;
}

void XCalculatephase_Set_Offset(XCalculatephase *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCalculatephase_WriteReg(InstancePtr->Crtls_BaseAddress, XCALCULATEPHASE_CRTLS_ADDR_OFFSET_DATA, Data);
}

u32 XCalculatephase_Get_Offset(XCalculatephase *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCalculatephase_ReadReg(InstancePtr->Crtls_BaseAddress, XCALCULATEPHASE_CRTLS_ADDR_OFFSET_DATA);
    return Data;
}

void XCalculatephase_InterruptGlobalEnable(XCalculatephase *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCalculatephase_WriteReg(InstancePtr->Crtls_BaseAddress, XCALCULATEPHASE_CRTLS_ADDR_GIE, 1);
}

void XCalculatephase_InterruptGlobalDisable(XCalculatephase *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCalculatephase_WriteReg(InstancePtr->Crtls_BaseAddress, XCALCULATEPHASE_CRTLS_ADDR_GIE, 0);
}

void XCalculatephase_InterruptEnable(XCalculatephase *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XCalculatephase_ReadReg(InstancePtr->Crtls_BaseAddress, XCALCULATEPHASE_CRTLS_ADDR_IER);
    XCalculatephase_WriteReg(InstancePtr->Crtls_BaseAddress, XCALCULATEPHASE_CRTLS_ADDR_IER, Register | Mask);
}

void XCalculatephase_InterruptDisable(XCalculatephase *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XCalculatephase_ReadReg(InstancePtr->Crtls_BaseAddress, XCALCULATEPHASE_CRTLS_ADDR_IER);
    XCalculatephase_WriteReg(InstancePtr->Crtls_BaseAddress, XCALCULATEPHASE_CRTLS_ADDR_IER, Register & (~Mask));
}

void XCalculatephase_InterruptClear(XCalculatephase *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCalculatephase_WriteReg(InstancePtr->Crtls_BaseAddress, XCALCULATEPHASE_CRTLS_ADDR_ISR, Mask);
}

u32 XCalculatephase_InterruptGetEnabled(XCalculatephase *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCalculatephase_ReadReg(InstancePtr->Crtls_BaseAddress, XCALCULATEPHASE_CRTLS_ADDR_IER);
}

u32 XCalculatephase_InterruptGetStatus(XCalculatephase *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCalculatephase_ReadReg(InstancePtr->Crtls_BaseAddress, XCALCULATEPHASE_CRTLS_ADDR_ISR);
}

