// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xcalculatephase.h"

extern XCalculatephase_Config XCalculatephase_ConfigTable[];

XCalculatephase_Config *XCalculatephase_LookupConfig(u16 DeviceId) {
	XCalculatephase_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XCALCULATEPHASE_NUM_INSTANCES; Index++) {
		if (XCalculatephase_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XCalculatephase_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XCalculatephase_Initialize(XCalculatephase *InstancePtr, u16 DeviceId) {
	XCalculatephase_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XCalculatephase_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XCalculatephase_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

