// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XCALCULATEPHASE_H
#define XCALCULATEPHASE_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xcalculatephase_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Crtls_BaseAddress;
} XCalculatephase_Config;
#endif

typedef struct {
    u32 Crtls_BaseAddress;
    u32 IsReady;
} XCalculatephase;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XCalculatephase_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XCalculatephase_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XCalculatephase_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XCalculatephase_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XCalculatephase_Initialize(XCalculatephase *InstancePtr, u16 DeviceId);
XCalculatephase_Config* XCalculatephase_LookupConfig(u16 DeviceId);
int XCalculatephase_CfgInitialize(XCalculatephase *InstancePtr, XCalculatephase_Config *ConfigPtr);
#else
int XCalculatephase_Initialize(XCalculatephase *InstancePtr, const char* InstanceName);
int XCalculatephase_Release(XCalculatephase *InstancePtr);
#endif

void XCalculatephase_Start(XCalculatephase *InstancePtr);
u32 XCalculatephase_IsDone(XCalculatephase *InstancePtr);
u32 XCalculatephase_IsIdle(XCalculatephase *InstancePtr);
u32 XCalculatephase_IsReady(XCalculatephase *InstancePtr);
void XCalculatephase_EnableAutoRestart(XCalculatephase *InstancePtr);
void XCalculatephase_DisableAutoRestart(XCalculatephase *InstancePtr);
u32 XCalculatephase_Get_return(XCalculatephase *InstancePtr);

void XCalculatephase_Set_T_X(XCalculatephase *InstancePtr, u32 Data);
u32 XCalculatephase_Get_T_X(XCalculatephase *InstancePtr);
void XCalculatephase_Set_T_Y(XCalculatephase *InstancePtr, u32 Data);
u32 XCalculatephase_Get_T_Y(XCalculatephase *InstancePtr);
void XCalculatephase_Set_T_Z(XCalculatephase *InstancePtr, u32 Data);
u32 XCalculatephase_Get_T_Z(XCalculatephase *InstancePtr);
void XCalculatephase_Set_Offset(XCalculatephase *InstancePtr, u32 Data);
u32 XCalculatephase_Get_Offset(XCalculatephase *InstancePtr);

void XCalculatephase_InterruptGlobalEnable(XCalculatephase *InstancePtr);
void XCalculatephase_InterruptGlobalDisable(XCalculatephase *InstancePtr);
void XCalculatephase_InterruptEnable(XCalculatephase *InstancePtr, u32 Mask);
void XCalculatephase_InterruptDisable(XCalculatephase *InstancePtr, u32 Mask);
void XCalculatephase_InterruptClear(XCalculatephase *InstancePtr, u32 Mask);
u32 XCalculatephase_InterruptGetEnabled(XCalculatephase *InstancePtr);
u32 XCalculatephase_InterruptGetStatus(XCalculatephase *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
